Repository HarbourMasters/Shipwright, pull requests merged in 2022-09, with the labels that each got.

#1387 More options for Link's Pocket and Null Global Context safe `Item_Give`
  soh/soh/Enhancements/randomizer/3drando/settings.cpp
  soh/soh/Enhancements/randomizer/randomizer.cpp
  soh/soh/Enhancements/randomizer/randomizerTypes.h
  soh/src/code/z_parameter.c
  soh/src/code/z_sram.c
Labels: randomizer

#1433 Use 3drando item table for parsing spoiler names
  soh/soh/Enhancements/randomizer/3drando/hints.cpp
  soh/soh/Enhancements/randomizer/3drando/item.cpp
  soh/soh/Enhancements/randomizer/3drando/item.hpp
  soh/soh/Enhancements/randomizer/3drando/item_list.cpp
  soh/soh/Enhancements/randomizer/3drando/item_list.hpp
  soh/soh/Enhancements/randomizer/3drando/rando_main.cpp
  soh/soh/Enhancements/randomizer/3drando/rando_main.hpp
  soh/soh/Enhancements/randomizer/randomizer.cpp
Labels: randomizer

#1427 wiiu: package SoH as a homebrew bundle
  BUILDING.md
  Jenkinsfile
  scripts/wiiu/build.sh
  soh/CMakeLists.txt
Labels: wii u

#1335 Rando: Enhanced Magic Arrows
  soh/soh/Enhancements/randomizer/3drando/location_access/locacc_dodongos_cavern.cpp
  soh/soh/Enhancements/randomizer/3drando/location_access/locacc_ganons_castle.cpp
  soh/soh/Enhancements/randomizer/3drando/location_access/locacc_spirit_temple.cpp
  soh/soh/Enhancements/randomizer/3drando/logic.cpp
  soh/soh/Enhancements/randomizer/3drando/setting_descriptions.cpp
  soh/soh/Enhancements/randomizer/3drando/setting_descriptions.hpp
  soh/soh/Enhancements/randomizer/3drando/settings.cpp
  soh/soh/Enhancements/randomizer/3drando/settings.hpp
  soh/soh/Enhancements/randomizer/randomizer.cpp
  soh/soh/Enhancements/randomizer/randomizerTypes.h
  soh/soh/GameMenuBar.cpp
  soh/src/overlays/actors/ovl_Bg_Breakwall/z_bg_breakwall.c
  soh/src/overlays/actors/ovl_Bg_Ice_Shelter/z_bg_ice_shelter.c
  soh/src/overlays/actors/ovl_Bg_Jya_Lift/z_bg_jya_lift.c
  soh/src/overlays/actors/ovl_Obj_Lightswitch/z_obj_lightswitch.c
Labels: randomizer

#1332 Another fix for getting items near critters
  soh/src/overlays/actors/ovl_player_actor/z_player.c
Labels: bug, randomizer

#1486 Fix: Unbreak Wii U sliders
  soh/soh/GameMenuBar.cpp
  soh/soh/UIWidgets.cpp
Labels: wii u

#1329 Shopsanity
  soh/include/macros.h
  soh/include/z64save.h
  soh/soh/Enhancements/custom-message/CustomMessageTypes.h
  soh/soh/Enhancements/debugger/debugSaveEditor.cpp
  soh/soh/Enhancements/randomizer/3drando/settings.cpp
  soh/soh/Enhancements/randomizer/randomizer.cpp
  soh/soh/Enhancements/randomizer/randomizer.h
  soh/soh/Enhancements/randomizer/randomizerTypes.h
  soh/soh/Enhancements/randomizer/randomizer_inf.h
  soh/soh/Enhancements/randomizer/randomizer_item_tracker.cpp
  soh/soh/OTRGlobals.cpp
  soh/soh/OTRGlobals.h
  soh/soh/SaveManager.cpp
  soh/src/code/code_80097A00.c
  soh/src/code/z_en_item00.c
  soh/src/code/z_parameter.c
  soh/src/overlays/actors/ovl_En_GirlA/z_en_girla.c
  soh/src/overlays/actors/ovl_En_GirlA/z_en_girla.h
  soh/src/overlays/actors/ovl_En_Ossan/z_en_ossan.c
  soh/src/overlays/gamestates/ovl_file_choose/z_file_choose.c
Labels: randomizer

#1497 Rando: Add missing French Junk Hint + Wallets stuff
  soh/soh/Enhancements/randomizer/3drando/custom_messages.cpp
  soh/soh/Enhancements/randomizer/3drando/hint_list.cpp
  soh/soh/Enhancements/randomizer/3drando/item_list.cpp
  soh/soh/Enhancements/randomizer/randomizer.cpp
Labels: randomizer, merge ready

#1476 [#1336] Fix issues with gFasterHeavyBlockLift
  soh/src/code/z_onepointdemo.c
  soh/src/code/z_onepointdemo_data.inc
  soh/src/overlays/actors/ovl_Bg_Heavy_Block/z_bg_heavy_block.c
  soh/src/overlays/actors/ovl_player_actor/z_player.c
Labels: merge ready, want for rando v2

#1482 Add hack to load bss texture in ovl_En_Jsjutan (fixes #69)
  OTRExporter/OTRExporter/DisplayListExporter.cpp
  libultraship/libultraship/Lib/Fast3D/gfx_pc.cpp
  soh/src/overlays/actors/ovl_En_Jsjutan/z_en_jsjutan.c
Labels: merge ready

#1444 Add ability to disable fish randomly escaping
  soh/soh/GameMenuBar.cpp
  soh/src/overlays/actors/ovl_Fishing/z_fishing.c
Labels: want for rando v2

#1525 (resolved merge conflicts) Temporary Fishing Fix
  soh/soh/GameMenuBar.cpp
  soh/src/overlays/actors/ovl_Fishing/z_fishing.c
Labels: want for rando v2

#1369 [Bugfix] Fix Equipment Screen Colors
  soh/src/overlays/misc/ovl_kaleido_scope/z_kaleido_equipment.c
Labels: bug, merge ready

#1247 Autosave improvements
  BUILDING.md
  soh/include/functions.h
  soh/soh/GameMenuBar.cpp
  soh/soh/OTRGlobals.cpp
  soh/soh/OTRGlobals.h
  soh/src/code/z_parameter.c
  soh/src/code/z_play.c
Labels: merge ready

#1398 Disable game input when typing into a textfield
  libultraship/libultraship/ControlDeck.cpp
  libultraship/libultraship/ControlDeck.h
Labels: merge ready, lus

#1556 Handle window closing event to stop SoH
  libultraship/libultraship/Lib/Fast3D/gfx_sdl2.cpp
Labels: merge ready

#1557 Remove obsolete and outdated xcode project
  soh/macosx/PkgInfo
  soh/macosx/Xcode-Info.plist
  soh/macosx/otr-outputs.xcfilelist
  soh/soh.xcodeproj/project.pbxproj
  soh/soh.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  soh/soh.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  soh/soh.xcodeproj/xcshareddata/xcschemes/soh.xcscheme
Labels: merge ready

#1558 Update version in remaining spots
  CMakeLists.txt
  soh/macosx/Info.plist
Labels: merge ready

#1566 Don't disable keyboard when menuBar is shown and gControlNav is true
  libultraship/libultraship/ImGuiImpl.cpp
Labels: merge ready

#1578 Fix Ganondorf texture issues
  soh/src/overlays/actors/ovl_Boss_Ganon/z_boss_ganon.c
  soh/src/overlays/actors/ovl_En_Ganon_Mant/z_en_ganon_mant.c
Labels: merge ready

#1581 Only attempt to compile PulseAudioPlayer on Linux
  libultraship/libultraship/CMakeLists.txt
Labels: merge ready

#1585 Fix save corruption on switch
  soh/soh/SaveManager.cpp
Labels: merge ready

#1588 Feature: Allow choosing audio backend
  libultraship/libultraship/AudioPlayer.h
  libultraship/libultraship/CMakeLists.txt
  libultraship/libultraship/ImGuiImpl.cpp
  libultraship/libultraship/ImGuiImpl.h
  libultraship/libultraship/Window.cpp
  libultraship/libultraship/Window.h
  soh/soh/GameMenuBar.cpp
Labels: merge ready

#1606 [#1584] Undo the special rotation done for spiritual stones after they are purchased
  soh/src/overlays/actors/ovl_En_GirlA/z_en_girla.c
Labels: merge ready

#1607 [#1603] Ensure gFasterHeavyBlockLift only affects large silver rocks
  soh/src/overlays/actors/ovl_player_actor/z_player.c
Labels: merge ready

#1608 Wii U: Several fixes and improvements
  libultraship/libultraship/Console.cpp
  libultraship/libultraship/GameOverlay.cpp
  libultraship/libultraship/ImGuiImpl.cpp
  libultraship/libultraship/Lib/Fast3D/gfx_gx2.cpp
  libultraship/libultraship/Lib/Fast3D/gfx_gx2.h
  libultraship/libultraship/Lib/Fast3D/gx2_shader_gen.c
  libultraship/libultraship/Lib/Fast3D/gx2_shader_gen.h
  libultraship/libultraship/Lib/ImGui/backends/wiiu/imgui_impl_wiiu.cpp
  libultraship/libultraship/Lib/ImGui/imgui_widgets.cpp
  libultraship/libultraship/Lib/Mercury/Mercury.cpp
  soh/CMakeLists.txt
  soh/soh/Enhancements/cosmetics/CosmeticsEditor.cpp
  soh/soh/Enhancements/randomizer/3drando/random.cpp
  soh/soh/Enhancements/randomizer/randomizer_item_tracker.cpp
  soh/soh/GameMenuBar.cpp
  soh/soh/SaveManager.cpp
  soh/soh/UIWidgets.cpp
  soh/src/boot/missing_gcc_functions.c
Labels: merge ready, wii u

#1609 Change precision of float sliders
  soh/soh/UIWidgets.cpp
Labels: merge ready

#1624 Shopsanity - fix regression from removing BUY_BOMBCHU_5
  soh/soh/Enhancements/randomizer/3drando/shops.cpp
Labels: randomizer
