Repository HarbourMasters/Shipwright, pull requests merged in 2022-08, with the labels that each got.

#1001 Randomizer: Prevents blocking Song of Time check by shielding.
  soh/src/code/z_play.c
Labels: bug, randomizer

#1044 don't use signed ints for epochs
  soh/include/z64effect.h
  soh/src/code/z_actor.c
  soh/src/code/z_kankyo.c
  soh/src/code/z_lifemeter.c
  soh/src/overlays/actors/ovl_Bg_Dy_Yoseizo/z_bg_dy_yoseizo.h
  soh/src/overlays/actors/ovl_Bg_Jya_Megami/z_bg_jya_megami.h
  soh/src/overlays/actors/ovl_Bg_Spot00_Hanebasi/z_bg_spot00_hanebasi.c
  soh/src/overlays/actors/ovl_Boss_Dodongo/z_boss_dodongo.h
  soh/src/overlays/actors/ovl_Boss_Fd/z_boss_fd.c
  soh/src/overlays/actors/ovl_Boss_Fd2/z_boss_fd2.h
  soh/src/overlays/actors/ovl_Boss_Ganon/z_boss_ganon.c
  soh/src/overlays/actors/ovl_Boss_Ganon2/z_boss_ganon2.c
  soh/src/overlays/actors/ovl_Boss_Mo/z_boss_mo.c
  soh/src/overlays/actors/ovl_Boss_Sst/z_boss_sst.c
  soh/src/overlays/actors/ovl_Boss_Sst/z_boss_sst.h
  soh/src/overlays/actors/ovl_Boss_Tw/z_boss_tw.c
  soh/src/overlays/actors/ovl_Boss_Tw/z_boss_tw.h
  soh/src/overlays/actors/ovl_Boss_Va/z_boss_va.c
  soh/src/overlays/actors/ovl_Demo_6K/z_demo_6k.c
  soh/src/overlays/actors/ovl_Demo_Kankyo/z_demo_kankyo.c
  soh/src/overlays/actors/ovl_Efc_Erupc/z_efc_erupc.h
  soh/src/overlays/actors/ovl_Eff_Dust/z_eff_dust.c
  soh/src/overlays/actors/ovl_En_Anubice_Fire/z_en_anubice_fire.h
  soh/src/overlays/actors/ovl_En_Ba/z_en_ba.h
  soh/src/overlays/actors/ovl_En_Bx/z_en_bx.h
  soh/src/overlays/actors/ovl_En_Clear_Tag/z_en_clear_tag.h
  soh/src/overlays/actors/ovl_En_Encount2/z_en_encount2.h
  soh/src/overlays/actors/ovl_En_Fd/z_en_fd.h
  soh/src/overlays/actors/ovl_En_Fw/z_en_fw.h
  soh/src/overlays/actors/ovl_En_Fz/z_en_fz.h
  soh/src/overlays/actors/ovl_En_G_Switch/z_en_g_switch.h
  soh/src/overlays/actors/ovl_En_Gb/z_en_gb.h
  soh/src/overlays/actors/ovl_En_Go/z_en_go.h
  soh/src/overlays/actors/ovl_En_Niw/z_en_niw.h
  soh/src/overlays/actors/ovl_En_Nwc/z_en_nwc.h
  soh/src/overlays/actors/ovl_En_Ny/z_en_ny.h
  soh/src/overlays/actors/ovl_En_Po_Sisters/z_en_po_sisters.h
  soh/src/overlays/actors/ovl_En_Syateki_Niw/z_en_syateki_niw.h
  soh/src/overlays/actors/ovl_En_Tk/z_en_tk.h
  soh/src/overlays/actors/ovl_En_Viewer/z_en_viewer.h
  soh/src/overlays/actors/ovl_Fishing/z_fishing.c
  soh/src/overlays/actors/ovl_Mir_Ray/z_mir_ray.c
  soh/src/overlays/effects/ovl_Effect_Ss_Bomb2/z_eff_ss_bomb2.h
Labels: merge ready

#1019 Add shuffleCows options for randomizer
  soh/include/z64save.h
  soh/soh/Enhancements/randomizer/3drando/settings.cpp
  soh/soh/Enhancements/randomizer/randomizer.cpp
  soh/soh/Enhancements/randomizer/randomizerTypes.h
  soh/soh/SaveManager.cpp
  soh/src/code/z_sram.c
  soh/src/overlays/actors/ovl_En_Cow/z_en_cow.c
Labels: randomizer

#1012 Handle audio thread properly
  libultraship/libultraship/Lib/Fast3D/gfx_dxgi.cpp
  libultraship/libultraship/Lib/Fast3D/gfx_sdl2.cpp
  soh/soh/OTRAudio.h
  soh/soh/OTRGlobals.cpp
  soh/src/code/graph.c
  soh/src/code/main.c
Labels: merge ready

#941 Changed input disable to only be forced on switch
  libultraship/libultraship/ControlDeck.cpp
  libultraship/libultraship/ImGuiImpl.cpp
  libultraship/libultraship/Window.cpp
Labels: merge ready

#1042 Rando: Prevent Ruto from disappearing in Jabu
  soh/src/overlays/actors/ovl_En_Ru1/z_en_ru1.c
Labels: merge ready

#1138 Fix Save Editor Event Check Inf "A" Row flags
  soh/soh/Enhancements/debugger/debugSaveEditor.cpp
Labels: merge ready

#1252 Rando: Fix Fast File Select seed loading
  soh/src/overlays/gamestates/ovl_title/z_title.c
Labels: randomizer

#1327 Properly handles starting link with adult trade items.
  soh/src/code/z_sram.c
Labels: bug, randomizer
