Repository HarbourMasters/Shipwright, pull requests merged in 2022-10, with the labels that each got.

#1637 chore: increment version to bravo
  CMakeLists.txt
  soh/macosx/Info.plist
  soh/src/boot/build.c
Labels: merge ready

#1636 fix: match auto center option text to behavior
  soh/soh/Enhancements/controls/GameControlEditor.cpp
  soh/soh/GameMenuBar.cpp
  soh/src/overlays/actors/ovl_player_actor/z_player.c
Labels: merge ready

#1692 Fix skipping "get item" cutscene logic
  soh/src/overlays/actors/ovl_player_actor/z_player.c
Labels: bug, merge ready

#1731 Implement G_CCMUX_NOISE (fixes #73, #72)
  libultraship/libultraship/Lib/Fast3D/gfx_cc.h
  libultraship/libultraship/Lib/Fast3D/gfx_direct3d_common.cpp
  libultraship/libultraship/Lib/Fast3D/gfx_opengl.cpp
  libultraship/libultraship/Lib/Fast3D/gfx_pc.cpp
Labels: libultraship

#1702 [#1671] Re-create textures from scratch & fix windows ZAPD issue
  OTRExporter/assets/textures/parameter_static/gDPad.ia16.png
  OTRExporter/assets/textures/title_static/gFileSelMQButtonTex.ia16.png
  OTRExporter/assets/textures/title_static/gFileSelRANDButtonTex.ia16.png
  ZAPDTR/ZAPD/Globals.cpp
Labels: merge ready

#1696 Support for patching DLists outside of OTR
  soh/soh/OTRGlobals.cpp
  soh/soh/OTRGlobals.h
  soh/src/code/z_kankyo.c
Labels: merge ready

#1728 Fix "Mask Select in Inventory" cycling bottle contents when bottle duping
  soh/src/overlays/misc/ovl_kaleido_scope/z_kaleido_item.c
Labels: merge ready

#1757 Fix: "Developer Tools" button sizes
  soh/soh/GameMenuBar.cpp
Labels: merge ready

#1752 Fix Gerudo Warrior Clothing
  soh/soh/GameMenuBar.cpp
  soh/src/overlays/actors/ovl_En_Ge3/z_en_ge3.c
Labels: merge ready

#1753 Implement Color Clamping
  libultraship/libultraship/Lib/Fast3D/gfx_direct3d_common.cpp
  libultraship/libultraship/Lib/Fast3D/gfx_opengl.cpp
  libultraship/libultraship/Window.cpp
Labels: libultraship

#1818 Use macros for max key count
  soh/include/macros.h
  soh/soh/Enhancements/randomizer/randomizer.cpp
  soh/soh/Enhancements/randomizer/randomizer_item_tracker.cpp
  soh/soh/OTRGlobals.cpp
Labels: merge ready

#1778 Chest size and texture matches contents
  OTRExporter/assets/objects/object_box/gGoldTreasureChestFrontTex.rgb5a1.png
  OTRExporter/assets/objects/object_box/gGoldTreasureChestSideAndTopTex.rgb5a1.png
  OTRExporter/assets/objects/object_box/gKeyTreasureChestFrontTex.rgb5a1.png
  OTRExporter/assets/objects/object_box/gKeyTreasureChestSideAndTopTex.rgb5a1.png
  OTRExporter/assets/objects/object_box/gSkullTreasureChestFrontTex.rgb5a1.png
  OTRExporter/assets/objects/object_box/gSkullTreasureChestSideAndTopTex.rgb5a1.png
  soh/soh/Enhancements/item-tables/ItemTableTypes.h
  soh/soh/Enhancements/randomizer/randomizer.cpp
  soh/soh/Enhancements/randomizer/randomizer.h
  soh/soh/GameMenuBar.cpp
  soh/soh/OTRGlobals.cpp
  soh/soh/OTRGlobals.h
  soh/src/overlays/actors/ovl_Bg_Mori_Hineri/z_bg_mori_hineri.c
  soh/src/overlays/actors/ovl_En_Box/z_en_box.c
  soh/src/overlays/actors/ovl_En_Box/z_en_box.h
Labels: merge ready

#1755 Rando: Starting Age fixes
  soh/soh/Enhancements/randomizer/3drando/settings.cpp
  soh/soh/Enhancements/randomizer/randomizer.cpp
  soh/src/code/z_sram.c
Labels: merge ready

#1812 Adds option to lock a cosmetic from being randomized
  soh/soh/Enhancements/cosmetics/CosmeticsEditor.cpp
  soh/soh/UIWidgets.cpp
Labels: merge ready

#1644 Add cheat for removing age restrictions on items
  soh/include/macros.h
  soh/soh/GameMenuBar.cpp
  soh/src/code/z_player_lib.c
  soh/src/overlays/misc/ovl_kaleido_scope/z_kaleido_equipment.c
  soh/src/overlays/misc/ovl_kaleido_scope/z_kaleido_item.c
Labels: enhancement

#1817 Adds camera sensitivity option back
  soh/soh/Enhancements/controls/GameControlEditor.cpp
  soh/src/code/z_camera.c
  soh/src/overlays/actors/ovl_player_actor/z_player.c
Labels: merge ready

#1831 Add quotes around the romfile to capture spaces and other characters.
  scripts/linux/appimage/soh.sh
Labels: merge ready

#1833 Fixes saving `isMasterQuest` and fixes default values for rando sliders.
  soh/soh/Enhancements/randomizer/randomizer.cpp
  soh/soh/SaveManager.cpp
Labels: randomizer, merge ready

#1133 Time Savers: Ask to Equip New Items
  soh/soh/GameMenuBar.cpp
  soh/soh/OTRGlobals.cpp
  soh/soh/OTRGlobals.h
  soh/src/code/z_message_PAL.c
  soh/src/overlays/actors/ovl_player_actor/z_player.c
Labels: merge ready

#1839 Ship::BinaryReader::ReadString: Fix endian issue
  libultraship/libultraship/BinaryReader.cpp
Labels: wiiu, libultraship

#1845 Fix LACS ganon's key hint text coloring and new lines
  soh/soh/Enhancements/randomizer/3drando/hint_list.cpp
Labels: merge ready

#1862 Fix Piece of Heart sound
  soh/src/overlays/actors/ovl_player_actor/z_player.c
Labels: merge ready
