Repository HarbourMasters/Shipwright, pull requests merged in 2023-01, with the labels that each got.

#2286 FIX: Equip now message
  soh/soh/OTRGlobals.cpp
Labels: merge ready

#2291 fix: properly randomize mirror shield and silver gaunts chests
  soh/soh/Enhancements/randomizer/randomizer_check_objects.cpp
Labels: merge ready

#2294 Remove repeated preset entries
  soh/soh/Enhancements/presets.h
Labels: merge ready

#2295 Fix Ganon Boss Key for MQ only otrs
  soh/soh/Enhancements/randomizer/randomizer_check_objects.cpp
Labels: merge ready

#2311 Altered save flag docs concerning events in Mido's house
  soh/soh/Enhancements/debugger/debugSaveEditor.h
Labels: merge ready

#2306 Map Select: Disable warning sound (BEL) sound by default
  soh/include/vt.h
  soh/src/boot/z_std_dma.c
  soh/src/code/game.c
  soh/src/code/graph.c
  soh/src/code/irqmgr.c
  soh/src/overlays/gamestates/ovl_select/z_select.c
Labels: merge ready

#2352 Fix: Wrong entrances in Epona state handler for ER
  soh/soh/Enhancements/randomizer/randomizer_entrance.c
Labels: merge ready

#2068 changes to the asset extraction script
  OTRExporter/extract_assets.py
  OTRExporter/rom_chooser.py
Labels: merge ready

#2225 Adds lock/unlock all buttons to Cosmetics Editor.
  soh/soh/Enhancements/cosmetics/CosmeticsEditor.cpp
Labels: feature

#2237 Adds option for showing sequence names on the overlay
  soh/soh/Enhancements/sfx-editor/SfxEditor.cpp
  soh/soh/Enhancements/sfx-editor/SfxEditor.h
  soh/src/code/audio_load.c
Labels: merge ready, feature

#2246 Adds option to add higher pitches to silver rupee jingle
  soh/soh/Enhancements/presets.h
  soh/soh/GameMenuBar.cpp
  soh/src/overlays/actors/ovl_En_G_Switch/z_en_g_switch.c
Labels: merge ready, feature

#2299 add OPTIONAL flag to avaid error when OTRGui is not build
  OTRGui/CMakeLists.txt
Labels: merge ready

#1947 Rando: Misc. Hints
  soh/include/z64save.h
  soh/soh/Enhancements/custom-message/CustomMessageTypes.h
  soh/soh/Enhancements/presets.h
  soh/soh/Enhancements/randomizer/3drando/fill.cpp
  soh/soh/Enhancements/randomizer/3drando/hints.cpp
  soh/soh/Enhancements/randomizer/3drando/hints.hpp
  soh/soh/Enhancements/randomizer/3drando/keys.hpp
  soh/soh/Enhancements/randomizer/3drando/settings.cpp
  soh/soh/Enhancements/randomizer/3drando/settings.hpp
  soh/soh/Enhancements/randomizer/3drando/spoiler_log.cpp
  soh/soh/Enhancements/randomizer/randomizer.cpp
  soh/soh/Enhancements/randomizer/randomizer.h
  soh/soh/Enhancements/randomizer/randomizerTypes.h
  soh/soh/OTRGlobals.cpp
  soh/soh/SaveManager.cpp
  soh/src/code/z_message_PAL.c
Labels: merge ready, merge conflicts

#2230 Tweak - Rando freestanding/skulltula ice trap behaviour
  soh/src/overlays/actors/ovl_En_Si/z_en_si.c
  soh/src/overlays/actors/ovl_player_actor/z_player.c
Labels: merge ready

#2332 Update BUILDING.md
  BUILDING.md
Labels: merge ready

#2376 fix: return enum value so mido moves away properly
  soh/src/overlays/actors/ovl_En_Md/z_en_md.c
Labels: merge ready

#2321 Rando - Ganon & Ganondorf cutscene skips
  soh/src/code/z_demo.c
  soh/src/overlays/actors/ovl_Boss_Ganon/z_boss_ganon.c
  soh/src/overlays/actors/ovl_Boss_Ganon2/z_boss_ganon2.c
  soh/src/overlays/actors/ovl_Boss_Ganon2/z_boss_ganon2.h
Labels: merge ready

#2322 Enhancement: MM-Style Static Explosion Radius
  soh/soh/Enhancements/presets.h
  soh/soh/GameMenuBar.cpp
  soh/src/overlays/actors/ovl_En_Bom/z_en_bom.c
Labels: merge ready

#1857 implement audio backend fallbacks
  soh/soh/OTRGlobals.cpp
Labels: do not merge, libultraship

#2378 Add reset/randomize all SFX and Cosmetic commands to console
  soh/soh/Enhancements/cosmetics/CosmeticsEditor.cpp
  soh/soh/Enhancements/cosmetics/CosmeticsEditor.h
  soh/soh/Enhancements/debugconsole.cpp
  soh/soh/Enhancements/sfx-editor/SfxEditor.cpp
  soh/soh/Enhancements/sfx-editor/SfxEditor.h
Labels: merge ready

#2178 Add cheat for extending hookshot reach
  soh/soh/GameMenuBar.cpp
  soh/src/code/z_player_lib.c
  soh/src/overlays/actors/ovl_Arms_Hook/z_arms_hook.c
Labels: merge ready

#2406 TWEAK: Forgot some translation on Debug Warp Screen
  soh/src/overlays/gamestates/ovl_select/z_select.c
Labels: merge ready

#2405 Clear cvars that lock up randomizer menu on boot
  soh/soh/Enhancements/bootcommands.c
Labels: merge ready

#2403 Fix: Quit Game
  soh/soh/Enhancements/debugconsole.cpp
Labels: merge ready

#2413 Fix: Override jail capture for the Gerudo fighter
  soh/soh/Enhancements/randomizer/randomizer_entrance.c
  soh/src/overlays/actors/ovl_En_GeldB/z_en_geldb.c
Labels: merge ready

#2414 Check tracker - Set default size and add X to close window
  soh/soh/Enhancements/randomizer/randomizer_check_tracker.cpp
Labels: merge ready

#2410 Fix: Chest Sizes Match Contents makes some chests unreachable
  soh/src/overlays/actors/ovl_En_Box/z_en_box.c
Labels: merge ready

#2416 TWEAK: GS Misspelling "Gold" in German + Box formating
  soh/soh/z_message_OTR.cpp
Labels: merge ready

#2407 TWEAK: Controller Navigation rename + tooltip
  soh/soh/GameMenuBar.cpp
Labels: merge ready
