Repository HarbourMasters/Shipwright, pull requests merged in 2023-06, with the labels that each got.

#2918 Enhancement: Show Gauntlets in First Person
  soh/soh/Enhancements/presets.h
  soh/soh/GameMenuBar.cpp
  soh/src/code/z_player_lib.c
Labels: merge ready

#1729 Dynamic Actor IDs
  soh/CMakeLists.txt
  soh/include/fp.h
  soh/include/functions.h
  soh/include/global.h
  soh/include/tables/actor_table.h
  soh/include/variables.h
  soh/include/z64actor.h
  soh/soh/ActorDB.cpp
  soh/soh/ActorDB.h
  soh/soh/Enhancements/debugconsole.cpp
  soh/soh/Enhancements/debugger/actorViewer.cpp
  soh/soh/OTRGlobals.cpp
  soh/src/code/z_actor.c
  soh/src/code/z_actor_dlftbls.c
  soh/src/code/z_play.c
  soh/src/code/z_scene.c
  soh/src/overlays/actors/ovl_En_Heishi1/z_en_heishi1.c
  soh/src/overlays/actors/ovl_En_Partner/z_en_partner.c
  soh/src/overlays/actors/ovl_En_Partner/z_en_partner.h
Labels: merge conflicts

#2923 [Feature] Boss Rush
  OTRExporter/assets/objects/object_mag/gTitleBossRushSubtitleTex.rgba32.png
  OTRExporter/assets/textures/parameter_static/gArrowDown.ia16.png
  OTRExporter/assets/textures/parameter_static/gArrowUp.ia16.png
  OTRExporter/assets/textures/title_static/gFileSelBossRushSettingsENGTex.ia8.png
  OTRExporter/assets/textures/title_static/gFileSelBossRushSettingsFRATex.ia8.png
  OTRExporter/assets/textures/title_static/gFileSelBossRushSettingsGERTex.ia8.png
  soh/assets/soh_assets.h
  soh/include/functions.h
  soh/include/z64.h
  soh/include/z64save.h
  soh/soh/Enhancements/boss-rush/BossRush.cpp
  soh/soh/Enhancements/boss-rush/BossRush.h
  soh/soh/Enhancements/boss-rush/BossRushTypes.h
  soh/soh/Enhancements/custom-message/CustomMessageInterfaceAddon.h
  soh/soh/Enhancements/custom-message/CustomMessageManager.cpp
  soh/soh/Enhancements/custom-message/CustomMessageManager.h
  soh/soh/Enhancements/debugger/debugSaveEditor.cpp
  soh/soh/Enhancements/gameplaystats.cpp
  soh/soh/Enhancements/gameplaystats.h
  soh/soh/Enhancements/mods.cpp
  soh/soh/OTRGlobals.h
  soh/soh/SaveManager.cpp
  soh/soh/z_play_otr.cpp
  soh/src/code/z_kaleido_scope_call.c
  soh/src/code/z_kanfont.c
  soh/src/code/z_message_PAL.c
  soh/src/code/z_parameter.c
  soh/src/code/z_play.c
  soh/src/code/z_sram.c
  soh/src/overlays/actors/ovl_Bg_Breakwall/z_bg_breakwall.c
  soh/src/overlays/actors/ovl_Boss_Dodongo/z_boss_dodongo.c
  soh/src/overlays/actors/ovl_Boss_Fd/z_boss_fd.c
  soh/src/overlays/actors/ovl_Boss_Fd2/z_boss_fd2.c
  soh/src/overlays/actors/ovl_Boss_Ganon/z_boss_ganon.c
  soh/src/overlays/actors/ovl_Boss_Ganon2/z_boss_ganon2.c
  soh/src/overlays/actors/ovl_Boss_Ganondrof/z_boss_ganondrof.c
  soh/src/overlays/actors/ovl_Boss_Goma/z_boss_goma.c
  soh/src/overlays/actors/ovl_Boss_Mo/z_boss_mo.c
  soh/src/overlays/actors/ovl_Boss_Sst/z_boss_sst.c
  soh/src/overlays/actors/ovl_Boss_Tw/z_boss_tw.c
  soh/src/overlays/actors/ovl_Boss_Va/z_boss_va.c
  soh/src/overlays/actors/ovl_Demo_Sa/z_demo_sa.c
  soh/src/overlays/actors/ovl_Door_Warp1/z_door_warp1.c
  soh/src/overlays/actors/ovl_En_Box/z_en_box.c
  soh/src/overlays/actors/ovl_En_Kusa/z_en_kusa.c
  soh/src/overlays/actors/ovl_Obj_Tsubo/z_obj_tsubo.c
  soh/src/overlays/actors/ovl_player_actor/z_player.c
  soh/src/overlays/gamestates/ovl_file_choose/file_choose.h
  soh/src/overlays/gamestates/ovl_file_choose/z_file_choose.c
  soh/src/overlays/misc/ovl_kaleido_scope/z_kaleido_scope_PAL.c
Labels: merge ready

#2958 Fix: Minimap dungeon entrance placement
  soh/src/code/z_map_exp.c
Labels: merge ready

#2962 only green the greg bridge not everything else
  OTRExporter/assets/helpers/cosmetics/gEndGrayscaleAndEndDlistDL
  soh/soh/Enhancements/cosmetics/CosmeticsEditor.cpp
  soh/soh/OTRGlobals.cpp
Labels: libultraship

#2966 Config versioning to fix the Fullscreen Shortcut debacle
  soh/CMakeLists.txt
  soh/soh/OTRGlobals.cpp
  soh/soh/config/ConfigUpdaters.cpp
  soh/soh/config/ConfigUpdaters.h
Labels: libultraship

#2955 fullscreen with f11 not f9
  README.md
  soh/soh/SohMenuBar.cpp
Labels: libultraship

#2974 Boss Rush - Fix missing goron bracelet
  soh/soh/Enhancements/boss-rush/BossRush.cpp
Labels: merge ready

#2973 Boss Rush - Fix RTA timer
  soh/src/code/z_parameter.c
Labels: merge ready

#2970 Fix: crash when resetting links scale without a playstate
  soh/soh/Enhancements/cosmetics/CosmeticsEditor.cpp
Labels: merge ready

#2956 properly set imgui invert aiming y default
  soh/soh/Enhancements/controls/GameControlEditor.cpp
Labels: merge ready

#2961 Fix: Cosmetic HUD placement reset position corrupting ship json
  soh/soh/Enhancements/cosmetics/CosmeticsEditor.cpp
Labels: merge ready

#3005 Add Mirror World gfx patches and patch Royal Grave Sun Song etching
  soh/soh/Enhancements/cosmetics/authenticGfxPatches.cpp
  soh/soh/Enhancements/cosmetics/authenticGfxPatches.h
  soh/soh/Enhancements/mods.cpp
Labels: merge ready

#3004 caps for locations in altar text
  soh/soh/Enhancements/randomizer/3drando/hints.cpp
Labels: merge ready

#2988 hide menu bar from menu bar
  soh/soh/SohMenuBar.cpp
Labels: merge ready

#3006 Tweak: Order spoiler log print out to match insertion order
  soh/soh/Enhancements/randomizer/3drando/spoiler_log.cpp
Labels: merge ready

#2874 Add option to prevent speed modifier from affecting jump velocity
  soh/soh/Enhancements/controls/GameControlEditor.cpp
  soh/src/overlays/actors/ovl_player_actor/z_player.c
Labels: merge ready

#2944 Add option for time travel to work with OoT or Any Ocarina
  soh/soh/Enhancements/mods.cpp
  soh/soh/SohMenuBar.cpp
Labels: merge ready

#3013 Tweak: Update Mac and Linux launch scripts to make mods dir
  scripts/linux/appimage/soh.sh
  soh/macosx/soh-macos.sh
Labels: merge ready

#3039 update hash docs
  README.md
  docs/supportedHashes.json
Labels: merge ready
