Repository HarbourMasters/Shipwright, pull requests merged in 2023-10, with the labels that each got.

#2837 Clear Cutscene Pointer Button/Cheat
  soh/soh/Enhancements/game-interactor/GameInteractor.h
  soh/soh/Enhancements/game-interactor/GameInteractor_RawAction.cpp
  soh/soh/SohMenuBar.cpp
Labels: merge conflicts

#2668 Check Tracker Update
  soh/include/z64save.h
  soh/soh/Enhancements/game-interactor/GameInteractor.h
  soh/soh/Enhancements/game-interactor/GameInteractor_Hooks.cpp
  soh/soh/Enhancements/game-interactor/GameInteractor_Hooks.h
  soh/soh/Enhancements/gameplaystats.cpp
  soh/soh/Enhancements/randomizer/randomizer.cpp
  soh/soh/Enhancements/randomizer/randomizer.h
  soh/soh/Enhancements/randomizer/randomizerTypes.h
  soh/soh/Enhancements/randomizer/randomizer_check_objects.cpp
  soh/soh/Enhancements/randomizer/randomizer_check_tracker.cpp
  soh/soh/Enhancements/randomizer/randomizer_check_tracker.h
  soh/soh/Enhancements/randomizer/randomizer_entrance_tracker.cpp
  soh/soh/Enhancements/randomizer/randomizer_entrance_tracker.h
  soh/soh/Enhancements/randomizer/randomizer_item_tracker.cpp
  soh/soh/OTRGlobals.cpp
  soh/soh/OTRGlobals.h
  soh/soh/SaveManager.cpp
  soh/soh/UIWidgets.cpp
  soh/soh/UIWidgets.hpp
  soh/src/code/z_message_PAL.c
  soh/src/code/z_play.c
  soh/src/overlays/actors/ovl_En_Ossan/z_en_ossan.c
Labels: blocking

#3276 TWEAK: Add transition to the Time Travel feature
  soh/soh/Enhancements/mods.cpp
Labels: merge ready

#3277 Age Requirement Docs
  soh/include/macros.h
  soh/src/code/z_play.c
  soh/src/overlays/actors/ovl_player_actor/z_player.c
  soh/src/overlays/misc/ovl_kaleido_scope/z_kaleido_equipment.c
  soh/src/overlays/misc/ovl_kaleido_scope/z_kaleido_item.c
  soh/src/overlays/misc/ovl_kaleido_scope/z_kaleido_scope.h
  soh/src/overlays/misc/ovl_kaleido_scope/z_kaleido_scope_PAL.c
Labels: merge ready

#2981 Rando: Master Sword Shuffle
  soh/include/functions.h
  soh/include/z64save.h
  soh/soh/Enhancements/debugger/debugSaveEditor.h
  soh/soh/Enhancements/mods.cpp
  soh/soh/Enhancements/randomizer/3drando/hint_list.cpp
  soh/soh/Enhancements/randomizer/3drando/hint_list/hint_list_exclude_overworld.cpp
  soh/soh/Enhancements/randomizer/3drando/hints.cpp
  soh/soh/Enhancements/randomizer/3drando/hints.hpp
  soh/soh/Enhancements/randomizer/3drando/item_list.cpp
  soh/soh/Enhancements/randomizer/3drando/item_location.cpp
  soh/soh/Enhancements/randomizer/3drando/item_location.hpp
  soh/soh/Enhancements/randomizer/3drando/item_pool.cpp
  soh/soh/Enhancements/randomizer/3drando/keys.hpp
  soh/soh/Enhancements/randomizer/3drando/location_access/locacc_castle_town.cpp
  soh/soh/Enhancements/randomizer/3drando/location_access/locacc_death_mountain.cpp
  soh/soh/Enhancements/randomizer/3drando/location_access/locacc_deku_tree.cpp
  soh/soh/Enhancements/randomizer/3drando/location_access/locacc_dodongos_cavern.cpp
  soh/soh/Enhancements/randomizer/3drando/location_access/locacc_fire_temple.cpp
  soh/soh/Enhancements/randomizer/3drando/location_access/locacc_forest_temple.cpp
  soh/soh/Enhancements/randomizer/3drando/location_access/locacc_ganons_castle.cpp
  soh/soh/Enhancements/randomizer/3drando/location_access/locacc_gerudo_training_grounds.cpp
  soh/soh/Enhancements/randomizer/3drando/location_access/locacc_gerudo_valley.cpp
  soh/soh/Enhancements/randomizer/3drando/location_access/locacc_hyrule_field.cpp
  soh/soh/Enhancements/randomizer/3drando/location_access/locacc_ice_cavern.cpp
  soh/soh/Enhancements/randomizer/3drando/location_access/locacc_jabujabus_belly.cpp
  soh/soh/Enhancements/randomizer/3drando/location_access/locacc_kakariko.cpp
  soh/soh/Enhancements/randomizer/3drando/location_access/locacc_lost_woods.cpp
  soh/soh/Enhancements/randomizer/3drando/location_access/locacc_shadow_temple.cpp
  soh/soh/Enhancements/randomizer/3drando/location_access/locacc_spirit_temple.cpp
  soh/soh/Enhancements/randomizer/3drando/location_access/locacc_water_temple.cpp
  soh/soh/Enhancements/randomizer/3drando/location_access/locacc_zoras_domain.cpp
  soh/soh/Enhancements/randomizer/3drando/logic.cpp
  soh/soh/Enhancements/randomizer/3drando/logic.hpp
  soh/soh/Enhancements/randomizer/3drando/settings.cpp
  soh/soh/Enhancements/randomizer/3drando/settings.hpp
  soh/soh/Enhancements/randomizer/3drando/shops.cpp
  soh/soh/Enhancements/randomizer/3drando/spoiler_log.cpp
  soh/soh/Enhancements/randomizer/3drando/spoiler_log.hpp
  soh/soh/Enhancements/randomizer/draw.cpp
  soh/soh/Enhancements/randomizer/draw.h
  soh/soh/Enhancements/randomizer/randomizer.cpp
  soh/soh/Enhancements/randomizer/randomizerTypes.h
  soh/soh/Enhancements/randomizer/randomizer_check_objects.cpp
  soh/soh/Enhancements/randomizer/randomizer_check_tracker.cpp
  soh/soh/Enhancements/randomizer/randomizer_entrance.c
  soh/soh/Enhancements/randomizer/randomizer_inf.h
  soh/soh/Enhancements/randomizer/savefile.cpp
  soh/soh/OTRGlobals.cpp
  soh/src/code/z_game_over.c
  soh/src/code/z_parameter.c
  soh/src/code/z_play.c
  soh/src/code/z_sram.c
  soh/src/overlays/actors/ovl_Bg_Toki_Swd/z_bg_toki_swd.c
  soh/src/overlays/actors/ovl_Boss_Ganon2/z_boss_ganon2.c
  soh/src/overlays/actors/ovl_Fishing/z_fishing.c
  soh/src/overlays/actors/ovl_player_actor/z_player.c
  soh/src/overlays/misc/ovl_kaleido_scope/z_kaleido_scope_PAL.c
Labels: blocking

#3274 String copy util method and fix Save Manager string copy overflows
  soh/soh/Enhancements/gameplaystats.cpp
  soh/soh/Enhancements/randomizer/randomizer.cpp
  soh/soh/SaveManager.cpp
  soh/soh/SaveManager.h
  soh/soh/util.cpp
  soh/soh/util.h
Labels: merge ready

#3282 Player Equip Docs
  soh/include/z64item.h
  soh/soh/Enhancements/boss-rush/BossRush.cpp
  soh/soh/Enhancements/debugconsole.cpp
  soh/soh/Enhancements/debugger/debugSaveEditor.cpp
  soh/soh/Enhancements/game-interactor/GameInteractionEffect.cpp
  soh/soh/Enhancements/game-interactor/GameInteractor_RawAction.cpp
  soh/soh/Enhancements/mods.cpp
  soh/soh/Enhancements/randomizer/randomizer.cpp
  soh/soh/OTRGlobals.cpp
  soh/soh/SaveManager.cpp
  soh/src/code/code_80097A00.c
  soh/src/code/z_demo.c
  soh/src/code/z_elf_message.c
  soh/src/code/z_message_PAL.c
  soh/src/code/z_parameter.c
  soh/src/code/z_player_lib.c
  soh/src/code/z_sram.c
  soh/src/overlays/actors/ovl_Bg_Toki_Swd/z_bg_toki_swd.c
  soh/src/overlays/actors/ovl_Boss_Ganon2/z_boss_ganon2.c
  soh/src/overlays/actors/ovl_En_Dns/z_en_dns.c
  soh/src/overlays/actors/ovl_En_GirlA/z_en_girla.c
  soh/src/overlays/actors/ovl_En_Gm/z_en_gm.c
  soh/src/overlays/actors/ovl_En_Go/z_en_go.c
  soh/src/overlays/actors/ovl_En_Go2/z_en_go2.c
  soh/src/overlays/actors/ovl_En_Kz/z_en_kz.c
  soh/src/overlays/actors/ovl_En_Md/z_en_md.c
  soh/src/overlays/actors/ovl_En_Rr/z_en_rr.c
  soh/src/overlays/actors/ovl_En_Xc/z_en_xc.c
  soh/src/overlays/actors/ovl_player_actor/z_player.c
  soh/src/overlays/gamestates/ovl_file_choose/z_file_choose.c
  soh/src/overlays/misc/ovl_kaleido_scope/z_kaleido_debug.c
  soh/src/overlays/misc/ovl_kaleido_scope/z_kaleido_equipment.c
  soh/src/overlays/misc/ovl_kaleido_scope/z_kaleido_scope_PAL.c
Labels: merge ready
