Repository HarbourMasters/Shipwright, pull requests merged in 2023-05, with the labels that each got.

#2798 fix: extractor dialog No selection
  soh/soh/OTRGlobals.cpp
Labels: merge ready

#2780 GCC 13 support
  soh/soh/Enhancements/audio/AudioCollection.h
  soh/soh/Enhancements/custom-message/CustomMessageManager.h
  soh/soh/Enhancements/debugger/debugSaveEditor.h
  soh/soh/Enhancements/randomizer/3drando/cosmetics.hpp
  soh/soh/Enhancements/randomizer/3drando/custom_messages.hpp
  soh/soh/Enhancements/randomizer/3drando/spoiler_log.hpp
  soh/soh/Enhancements/randomizer/randomizer_entrance_tracker.h
  soh/soh/Enhancements/randomizer/randomizer_item_tracker.h
Labels: libultraship

#2899 Fixes buying songs crash on Switch
  soh/soh/Enhancements/game-interactor/GameInteractor_Hooks.h
  soh/soh/OTRGlobals.cpp
  soh/soh/OTRGlobals.h
  soh/src/code/z_parameter.c
Labels: merge ready

#2900 Mask Sale Fix
  soh/src/code/z_parameter.c
Labels: merge ready

#2904 Bunny Hood Unequip On Load Fix
  soh/include/variables.h
  soh/src/code/z_play.c
  soh/src/overlays/misc/ovl_kaleido_scope/z_kaleido_item.c
  soh/src/overlays/misc/ovl_kaleido_scope/z_kaleido_scope.h
Labels: merge ready

#2907 Add Scene Specific Checks to Dirt Path Fixes
  soh/soh/Enhancements/mods.cpp
  soh/soh/Enhancements/mods.h
  soh/soh/GameMenuBar.cpp
Labels: merge ready

#2862 Cleanup gameplay stats code/UI and support RTA timing
  soh/include/z64save.h
  soh/soh/Enhancements/gameplaystats.cpp
  soh/soh/Enhancements/gameplaystats.h
  soh/soh/GameMenuBar.cpp
  soh/soh/OTRGlobals.cpp
  soh/soh/OTRGlobals.h
  soh/soh/SaveManager.cpp
  soh/src/code/z_play.c
  soh/src/overlays/actors/ovl_Boss_Ganon2/z_boss_ganon2.c
Labels: merge ready

#2911 Add back missing Greg timestamp for Gameplay Stats
  soh/soh/Enhancements/gameplaystats.cpp
Labels: merge ready

#2890 Expose Thieves' Hideout selection for keyrings in randomizer settings
  soh/soh/Enhancements/presets.h
  soh/soh/Enhancements/randomizer/3drando/settings.cpp
  soh/soh/Enhancements/randomizer/draw.cpp
  soh/soh/Enhancements/randomizer/randomizer.cpp
  soh/soh/Enhancements/randomizer/randomizerTypes.h
Labels: merge ready

#2920 Fix: Use blue potion refill for Granny Shop item when unshuffled
  soh/soh/Enhancements/randomizer/3drando/item_pool.cpp
Labels: merge ready

#2919 Update README to include tools
  README.md
Labels: merge ready

#2889 Sectional Saves
  soh/include/z64save.h
  soh/soh/Enhancements/gameplaystats.cpp
  soh/soh/Enhancements/randomizer/randomizer_entrance.c
  soh/soh/SaveManager.cpp
  soh/soh/SaveManager.h
Labels: merge ready

#2913 Use gBuildVersion instead of sohStats.buildVersion for gameplay stats
  soh/soh/Enhancements/gameplaystats.cpp
Labels: merge ready, merge conflicts

#2887 Hyper Enemies (act and move twice as fast)
  soh/soh/Enhancements/mods.cpp
  soh/soh/GameMenuBar.cpp
Labels: merge ready

#2864 Improve Controller LED Control
  soh/include/z64.h
  soh/soh/Enhancements/controls/GameControlEditor.cpp
  soh/soh/GameMenuBar.cpp
  soh/soh/OTRGlobals.cpp
  soh/src/code/padmgr.c
Labels: merge ready

#2869 Update cvar clear lists and add cheatCvars clear list(not currently used)
  soh/soh/Enhancements/presets.h
Labels: merge ready

#2825 ShadowTag (7.0.1)
  soh/soh/Enhancements/mods.cpp
  soh/soh/GameMenuBar.cpp
  soh/src/overlays/actors/ovl_En_Wallmas/z_en_wallmas.c
  soh/src/overlays/actors/ovl_En_Wallmas/z_en_wallmas.h
Labels: merge ready
